# IO pin assignments for the AMC502 board #

proc false_path {patt clk} {
    set p [get_ports -quiet $patt -filter {direction != out}]
    if {llength $p != 0} {
        set_input_delay 0 -clock [get_clocks $clk] [get_ports $patt -filter {direction != out}]
        set_false_path -from [get_ports $patt -filter {direction != out}]
    }
    set p [get_ports -quiet $patt -filter {direction != in}]
    if {llength $p != 0} {
       	set_output_delay 0 -clock [get_clocks $clk] [get_ports $patt -filter {direction != in}]
	    set_false_path -to [get_ports $patt -filter {direction != in}]
	}
}

proc false_path_out {patt clk} {
	set_output_delay 0 -clock [get_clocks $clk] [get_ports $patt -filter {direction != in}]
	set_false_path -to [get_ports $patt -filter {direction != in}]
}

# Clock IO
set_property PACKAGE_PIN AK19 [get_ports {clk40_in_n}]
set_property IOSTANDARD LVDS_25 [get_ports {clk40_in_n}]
set_property DIFF_TERM FALSE [get_ports {clk40_in_n}]
set_property PACKAGE_PIN AK18 [get_ports {clk40_in_p}]
set_property IOSTANDARD LVDS_25 [get_ports {clk40_in_p}]
set_property DIFF_TERM FALSE [get_ports {clk40_in_p}]
set_property PACKAGE_PIN AH23 [get_ports {ttc_in_n}]
set_property IOSTANDARD LVDS_25 [get_ports {ttc_in_n}]
set_property DIFF_TERM FALSE [get_ports {ttc_in_n}]
set_property PACKAGE_PIN AG23 [get_ports {ttc_in_p}]
set_property IOSTANDARD LVDS_25 [get_ports {ttc_in_p}]
set_property DIFF_TERM FALSE [get_ports {ttc_in_p}]
set_property PACKAGE_PIN L7 [get_ports eth_clkn]
set_property PACKAGE_PIN L8 [get_ports eth_clkp]
set_input_delay 0 -clock [get_clocks clk_40_ext] [get_ports {ttc_in_*}]

# MGT refclk 111
set_property PACKAGE_PIN AJ7 [get_ports {refclkn[0]}]
set_property PACKAGE_PIN AJ8 [get_ports {refclkp[0]}]

# Front panel LEDs banks 12, 13, 13, 13
set_property slew slow [get_ports {leds_gpoi[*]}]
set_property iostandard lvcmos25 [get_ports {leds_gpoi[*]}]
set_property package_pin AC30 [get_ports {leds_gpoi[0]}]
set_property package_pin AD31 [get_ports {leds_gpoi[1]}]
set_property package_pin AM31 [get_ports {leds_gpoi[2]}]
set_property package_pin AD30 [get_ports {leds_gpoi[3]}]

### FMC0 LA pins ##
set_property package_pin E21 [get_ports {FMC0_LA00_CC_P}]
set_property package_pin E22 [get_ports {FMC0_LA00_CC_N}]
set_property package_pin E19 [get_ports {FMC0_LA01_CC_P}]
set_property package_pin D19 [get_ports {FMC0_LA01_CC_N}]
set_property package_pin M26 [get_ports {FMC0_LA02_P}]
set_property package_pin M27 [get_ports {FMC0_LA02_N}]
set_property package_pin J24 [get_ports {FMC0_LA03_P}]
set_property package_pin J25 [get_ports {FMC0_LA03_N}]
set_property package_pin L24 [get_ports {FMC0_LA04_P}]
set_property package_pin K24 [get_ports {FMC0_LA04_N}]
set_property package_pin K28 [get_ports {FMC0_LA05_P}]
set_property package_pin K29 [get_ports {FMC0_LA05_N}]
set_property package_pin L28 [get_ports {FMC0_LA06_P}]
set_property package_pin L29 [get_ports {FMC0_LA06_N}]
set_property package_pin K26 [get_ports {FMC0_LA07_P}]
set_property package_pin K27 [get_ports {FMC0_LA07_N}]
set_property package_pin H28 [get_ports {FMC0_LA08_P}]
set_property package_pin G28 [get_ports {FMC0_LA08_N}]
set_property package_pin F28 [get_ports {FMC0_LA09_P}]
set_property package_pin E28 [get_ports {FMC0_LA09_N}]
set_property package_pin D26 [get_ports {FMC0_LA10_P}]
set_property package_pin D27 [get_ports {FMC0_LA10_N}]
set_property package_pin H24 [get_ports {FMC0_LA11_P}]
set_property package_pin H25 [get_ports {FMC0_LA11_N}]
set_property package_pin J26 [get_ports {FMC0_LA12_P}]
set_property package_pin J27 [get_ports {FMC0_LA12_N}]
set_property package_pin B26 [get_ports {FMC0_LA13_P}]
set_property package_pin B27 [get_ports {FMC0_LA13_N}]
set_property package_pin B28 [get_ports {FMC0_LA14_P}]
set_property package_pin A28 [get_ports {FMC0_LA14_N}]
set_property package_pin G20 [get_ports {FMC0_LA15_P}]
set_property package_pin G21 [get_ports {FMC0_LA15_N}]
set_property package_pin F23 [get_ports {FMC0_LA16_P}]
set_property package_pin E23 [get_ports {FMC0_LA16_N}]
set_property package_pin E26 [get_ports {FMC0_LA17_CC_P}]
set_property package_pin E27 [get_ports {FMC0_LA17_CC_N}]
set_property package_pin H27 [get_ports {FMC0_LA18_CC_P}]
set_property package_pin G27 [get_ports {FMC0_LA18_CC_N}]
set_property package_pin D24 [get_ports {FMC0_LA19_P}]
set_property package_pin D25 [get_ports {FMC0_LA19_N}]
set_property package_pin F24 [get_ports {FMC0_LA20_P}]
set_property package_pin E24 [get_ports {FMC0_LA20_N}]
set_property package_pin B21 [get_ports {FMC0_LA21_P}]
set_property package_pin A21 [get_ports {FMC0_LA21_N}]
set_property package_pin C23 [get_ports {FMC0_LA22_P}]
set_property package_pin B23 [get_ports {FMC0_LA22_N}]
set_property package_pin G22 [get_ports {FMC0_LA23_P}]
set_property package_pin G23 [get_ports {FMC0_LA23_N}]
set_property package_pin C20 [get_ports {FMC0_LA24_P}]
set_property package_pin B20 [get_ports {FMC0_LA24_N}]
set_property package_pin A19 [get_ports {FMC0_LA25_P}]
set_property package_pin A20 [get_ports {FMC0_LA25_N}]
set_property package_pin B22 [get_ports {FMC0_LA26_P}]
set_property package_pin A23 [get_ports {FMC0_LA26_N}]
set_property package_pin F20 [get_ports {FMC0_LA27_P}]
set_property package_pin F21 [get_ports {FMC0_LA27_N}]
set_property package_pin C17 [get_ports {FMC0_LA28_P}]
set_property package_pin B17 [get_ports {FMC0_LA28_N}]
set_property package_pin B18 [get_ports {FMC0_LA29_P}]
set_property package_pin A18 [get_ports {FMC0_LA29_N}]
set_property package_pin D16 [get_ports {FMC0_LA30_P}]
set_property package_pin D17 [get_ports {FMC0_LA30_N}]
set_property package_pin B16 [get_ports {FMC0_LA31_P}]
set_property package_pin A16 [get_ports {FMC0_LA31_N}]
set_property package_pin F16 [get_ports {FMC0_LA32_P}]
set_property package_pin E16 [get_ports {FMC0_LA32_N}]
set_property package_pin E17 [get_ports {FMC0_LA33_P}]
set_property package_pin E18 [get_ports {FMC0_LA33_N}]
### SET FMC0 IOSTANDARD to LVCMOS 2,5V ##
set_property iostandard lvcmos25 [get_ports {FMC0*}]

### USER Switch input pins ##
set_property package_pin G16 [get_ports {user[0]}]
set_property package_pin F18 [get_ports {user[1]}]
set_property package_pin D22 [get_ports {user[2]}]
set_property package_pin H22 [get_ports {user[3]}]
set_property package_pin H23 [get_ports {user[4]}]
set_property package_pin M25 [get_ports {user[5]}]
set_property package_pin J29 [get_ports {user[6]}]
### SET USER Switch IOSTANDARD to LVCMOS 2,5V ##
set_property iostandard lvcmos25 [get_ports {user[*]}]

#TX_DISABLE,RATE_SEL#
## FMC1-F18 enable ##
# set_property iostandard lvcmos25 [get_ports {fmc1*}]
# #quad_0
# set_property package_pin af31 [get_ports {fmc1_la17_p}]
# set_property package_pin ac28 [get_ports {fmc1_la15_p}]
# set_property package_pin ab25 [get_ports {fmc1_la13_n}]
# set_property package_pin aa31 [get_ports {fmc1_la11_n}]
# set_property package_pin ab32 [get_ports {fmc1_la10_p}]
# set_property package_pin ab30 [get_ports {fmc1_la08_p}]
# set_property package_pin v28  [get_ports {fmc1_la06_n}]
# set_property package_pin w25  [get_ports {fmc1_la04_n}]
# #quad_1
# set_property package_pin an29 [get_ports {fmc1_la33_p}]
# set_property package_pin ap31 [get_ports {fmc1_la31_p}]
# set_property package_pin an34 [get_ports {fmc1_la29_n}]
# set_property package_pin al31 [get_ports {fmc1_la27_n}]
# set_property package_pin ak34 [get_ports {fmc1_la26_p}]
# set_property package_pin ah30 [get_ports {fmc1_la24_p}]
# set_property package_pin ag30 [get_ports {fmc1_la22_n}]
# set_property package_pin ae32 [get_ports {fmc1_la20_n}]

### FMC0-F18 enable ##
#set_property iostandard lvcmos25 [get_ports {fmc0*}]
##quad_2
#set_property package_pin e26  [get_ports {fmc0_la17_p}]
#set_property package_pin b22  [get_ports {fmc0_la15_p}]
#set_property package_pin a20  [get_ports {fmc0_la13_n}]
#set_property package_pin a18  [get_ports {fmc0_la11_n}]
#set_property package_pin b16  [get_ports {fmc0_la10_p}]
#set_property package_pin d16  [get_ports {fmc0_la08_p}]
#set_property package_pin g23  [get_ports {fmc0_la06_n}]
#set_property package_pin g21  [get_ports {fmc0_la04_n}]
##quad_3
#set_property package_pin l28  [get_ports {fmc0_la33_p}]
#set_property package_pin k26  [get_ports {fmc0_la31_p}]
#set_property package_pin k24  [get_ports {fmc0_la29_n}]
#set_property package_pin g28  [get_ports {fmc0_la27_n}]
#set_property package_pin h24  [get_ports {fmc0_la26_p}]
#set_property package_pin f28  [get_ports {fmc0_la24_p}]
#set_property package_pin d27  [get_ports {fmc0_la22_n}]
#set_property package_pin a28  [get_ports {fmc0_la20_n}]
